name: aws
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: xavier <xavier.hainaux@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0

dev_dependencies:
  analyzer: 0.38.2 # TODO(xha): Supprimer quand https://github.com/dart-lang/sdk/issues/38499
  build_runner:
  pedantic:
  test:
  json_annotation: ^3.0.0
  json_serializable: ^3.0.0
  html2md:
